services:
  selenoid:
    image: aerokube/selenoid:latest
    container_name: selenoid
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./browsers.json:/etc/selenoid/browsers.json:ro
    ports:
      - "4444:4444"
    command: >
      -limit 2
      -timeout 50m
      -service-startup-timeout 20m
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:4444/status" ]
      interval: 5s
      retries: 20
      start_period: 5s
      timeout: 2s

  tests:
    build:
      context: .
      dockerfile: Dockerfile.tests
    container_name: tests
    volumes:
      - .:/app
      - ./maven_cache:/root/.m2
    environment:
      - SELENOID_URL=http://selenoid:4444/wd/hub
    depends_on:
      selenoid:
        condition: service_healthy
    command: ["mvn", "clean", "test"]