services:
  selenoid:
    image: aerokube/selenoid:latest
    container_name: selenoid
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./browsers.json:/etc/selenoid/browsers.json:ro
    ports:
      - "4444:4444"
    command: >
      -limit 2
      -timeout 50m
      -service-startup-timeout 20m

  tests:
    build:
      context: .
      dockerfile: Dockerfile.tests
    container_name: tests
    volumes:
      - .:/app
      - ./maven_cache:/root/.m2
    depends_on:
      - selenoid
    environment:
      - SELENOID_URL=http://selenoid:4444/wd/hub
    command: ["mvn", "clean", "test"]